services:
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      CLUSTER_ID: "o0oqgfJkSRKy30HkVsAjBg"
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENERS: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://0.0.0.0:9092,CONTROLLER://kafka:29093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: kafka
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      # Configuration Event Sourcing - Conservation des messages
      KAFKA_LOG_RETENTION_HOURS: 168 # Garde les messages 7 jours
      KAFKA_LOG_RETENTION_BYTES: 1073741824 # Taille des partitions : 1GB
      KAFKA_LOG_SEGMENT_BYTES: 214748364 # Taille des log segments : 200MB (parties d'une partition sur le disque)
    healthcheck:
      test: kafka-broker-api-versions --bootstrap-server kafka:9092 || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - labo05-network

  coolriel:
    build: .
    container_name: coolriel
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - ./output:/app/output
    restart: unless-stopped
    networks:
      - labo05-network

networks:
  labo05-network:
    external: true
